### ISSUE TITLE
multer.diskStorage is not a function

### ISSUE THREAD

**Issue by Alexufo** [fox1t/multer#10]
hi, I have a strange behavior on my second project copy.

My code is working and when I ran `node  server.js` it on similar machine I get this error.
I reinstall npm project files, clear mode_modules,  rebooting - nothing.
Ubuntu18.

example
   ````
    const photoStorage = multer.diskStorage({})
    const photoUpload = multer({ storage: photoStorage })
    server.register(multer.contentParser)

    server.route({
        method: 'POST',
        url: '/photo',
        preHandler: photoUpload .single('photo-image'),
````

````
const passStorage = multer.diskStorage({
                           ^

TypeError: multer.diskStorage is not a function
    at module.exports (/home/aa/server/services/file-uploader.js:32:32)
    at Plugin.exec (/home/aa/server/node_modules/avvio/plugin.js:89:17)
    at Boot.loadPlugin (/home/aa/server/node_modules/avvio/plugin.js:175:10)
    at Task.release (/home/aa/server/node_modules/fastq/queue.js:127:16)
    at worked (/home/aa/server/node_modules/fastq/queue.js:169:10)
    at /home/aa/server/node_modules/avvio/plugin.js:178:7
    at done (/home/aa/server/node_modules/avvio/plugin.js:136:5)
    at check (/home/aa/server/node_modules/avvio/plugin.js:147:7)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
````
If I remove code with multer.diskStorage({}) - project will start

Multer installed, diskStorage present in /home/aa/server/node_modules/fastify-multer/lib/storage/disk.js

**Comment by fox1t** [comment]
HI! May I ask you to create a repository here on GitHub with the minimum code that can reproduce this issue and link it here?

**Comment by Alexufo** [comment]
May be better to send you ssh key for access to vm?

**Comment by fox1t** [comment]
Sorry I don't want to debug it on your systems. We need to understand if it is a bug/issue with fastify-multer or is just a problem of your execution environment. First step is to build a repro repo so that i can clone it and test it.

**Comment by Alexufo** [comment]
Copy of the project. Now it is just `multer is not a function`
https://github.com/Alexufo/testmulter

1. npm install
2. node server.js

**Comment by fox1t** [comment]
OK thanks for providing the repo. It seems an issue with commonjs requires. I am going to fix this right now.

**Comment by fox1t** [comment]
1.5.2 published, it is supposed to be fixed. I am going to close this issue, if you still have problems, feel free to reopen it.

**Comment by Alexufo** [comment]
yes. It worked. Thank you. But... can you suggest why 3 days ago it worked good? Is it reason of new version of fastify? :-)

**Comment by fox1t** [comment]
No, I updated fastify-multer and introduced a regression on commonjs: 1.5.0 worked, 1.5.1 has this issue, and 1.5.2 is working again. I introduced it to fix some TS related problems.
Sorry for this issue.
